### ISSUE TITLE
Pcg.exe and qdldl.exe crash at runtime

### ISSUE THREAD

**Issue by simomux** [A2R-Lab/MPCGPU#5]
**Issue Description:**

After following the compilation instructions outlined in the README.md from the main branch, both the `qdldl.exe` and `pcg.exe` programs crash at runtime, each producing the following error messages:

- `GPUassert: an illegal memory access was encountered include/qdldl/sqp.cuh 227`
- `GPUassert: an illegal memory access was encountered include/pcg/sqp.cuh 182`

**System Configuration:**

- Operating System: Ubuntu 22.04
- GPU: RTX 2070
- CUDA Version: 12.4

**Configuration Details:**

For the PCG Solver:
```
Knot points: 32
State size: 14
Datatype: FLOAT
Sqp exits condition: CONSTANT TIME
QD COST: 0.0001
R COST: 0.0001
Rho factor: 1.2
Rho max: 10
Test iters: 1
Max sqp time: 2000
Solver: PCG
Max pcg iter: 173
Save data: OFF
Jitters: ON

start: 0 goal: 0
Logging test results to files with prefix tmp/results/32_PCG_0.000005 
```

For the QDLDL Solver:
```
Knot points: 32
State size: 14
Datatype: FLOAT
Sqp exits condition: CONSTANT TIME
QD COST: 0.0001
R COST: 0.0001
Rho factor: 1.2
Rho max: 10
Test iters: 1
Max sqp time: 2000
Solver: QDLDL
Save data: OFF
Jitters: ON

start: 0 goal: 0
Logging test results to files with prefix tmp/results/32_QDLDL 
```

**Observations:**

It appears that the issue may be related to the `direct_minv_inner` function within `include/dynamics/iiwa/iiwa_eepos_grid.cuh` for both solvers. I think that the dynamically shared array `s_xux_k`, defined in `include/common/merit.cuh`, could be involved.

Sometimes only the first 128 threads successfully complete the `compute_merit` kernel, while the remaining threads segfaults in `direct_minv_inner`. However, this behavior isn't consistent, sometimes no thread is able to complete `compute_merit`.

**Request for Clarification:**

I'm uncertain whether this problem is related to a setup issue, something missing in my configuration, or if it's indicative of a bug within the codebase. Any insights or guidance on resolving this issue would be greatly appreciated.

**Comment by EmreAdabag** [comment]
Thanks for bringing this up! We hadn't tested on any GPUs older than 3000-series. Linked PR should address those issues
